resolver: lts-20.18

# Local packages, usually specified by relative directory name
packages:
- '.'

extra-deps:
# - unbound-generics-0.4.3.1
- git: git@github.com:liesnikov/unbound-generics.git
  commit: 04b33b774f6d27116232493135d58858a7ab35f4


flags: {}

extra-package-dbs: []
